"""
Django settings for parkcontrol project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from decouple import config, Csv


BASE_DIR = Path(__file__).resolve().parent.parent

# Carregando as variáveis do arquivo .env
SECRET_KEY = config('SECRET_KEY')

# O segundo argumento (default=False) é o valor padrão caso a variável não exista.
# O 'cast=bool' converte o valor lido ('True'/'False') para um booleano (True/False).
DEBUG = config('DEBUG', default=False, cast=bool)

# A função Csv da decouple é útil para converter uma string separada por vírgulas em uma lista Python.
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    # Apps nativos do Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simple_history',  # Para histórico de alterações nos modelos
    
    # Apps da aplicação
    'apps.clientes',
    'apps.core',  
    'apps.frentistas',
    'apps.usuarios',
    'apps.manutencao',
    'apps.pagamentos',
    'apps.planos',
    'apps.relatorios',
    'apps.vagas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # Middleware para histórico de alterações
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parkcontrol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_templates', # Diretório para templates base
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parkcontrol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'usuarios.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Cuiaba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## para testes com console
EMAIL_BACKEND = config('EMAIL_BACKEND')

EMAIL_HOST = config('EMAIL_HOST')           # servidor SMTP do provedor (exemplo Gmail)
EMAIL_USE_TLS = config('EMAIL_USE_TLS')                    # TLS para segurança
EMAIL_PORT = config('EMAIL_PORT')                       # porta do servidor SMTP
EMAIL_HOST_USER = config('EMAIL_HOST_USER')    # seu email
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detailed': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'clientes_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/clientes.log',
            'formatter': 'detailed',
        },
        'manutencao_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/manutencao.log',
            'formatter': 'detailed',
        },
        'pagamentos_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/pagamentos.log',
            'formatter': 'detailed',
        },
        'planos_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/planos.log',
            'formatter': 'detailed',
        },
        'relatorios_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/relatorios.log',
            'formatter': 'detailed',
        },
        'usuarios_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/usuarios.log',
            'formatter': 'detailed',
        },
        'vagas_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/vagas.log',
            'formatter': 'detailed',
        },
        'frentistas_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/frentistas.log',
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'clientes': {
            'handlers': ['clientes_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'manutencao': {
            'handlers': ['manutencao_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'pagamentos': {
            'handlers': ['pagamentos_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'planos': {
            'handlers': ['planos_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'relatorios': {
            'handlers': ['relatorios_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'usuarios': {
            'handlers': ['usuarios_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'vagas': {
            'handlers': ['vagas_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'frentistas': {
            'handlers': ['frentistas_file'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}
