# Generated by Django 5.2.1 on 2025-06-05 12:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Tarifa')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial')),
                ('valor_hora_adicional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor das Horas Adicionais')),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da diária')),
                ('valor_mensal_avulso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal Avulso')),
                ('ativa', models.BooleanField(default=True, verbose_name='Tarifa Ativa')),
            ],
            options={
                'verbose_name': 'Configuração de Tarifa',
                'verbose_name_plural': 'Configurações de Tarifas',
            },
        ),
        migrations.CreateModel(
            name='PlanoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=100, unique=True, verbose_name='Nome do Plano')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Mensalidade')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano Mensal',
                'verbose_name_plural': 'Planos Mensais',
            },
        ),
        migrations.CreateModel(
            name='ClienteMensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Plano')),
                ('email_para_cobranca', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail para Cobrança')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagamentos.planomensal', verbose_name='Plano Mensal')),
            ],
            options={
                'verbose_name': 'Cliente Mensalista',
                'verbose_name_plural': 'Clientes Mensalistas',
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_veiculo', models.CharField(max_length=8, verbose_name='Placa do Veículo')),
                ('hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Hora da Entrada')),
                ('hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora da Saída')),
                ('valor_total_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total Calculado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Movimento de Estacionamento',
                'verbose_name_plural': 'Movimentos de Estacionamento',
                'ordering': ['-hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaDiarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Adicional')),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.movimento', verbose_name='Movimento de Estacionamento')),
            ],
            options={
                'verbose_name': 'Cobrança de Diarista',
                'verbose_name_plural': 'Cobranças de Diaristas',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='CobrancaMensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('mes_referencia', models.CharField(help_text='Para cobranças mensais, ex: 05/2025', max_length=7, verbose_name='Mês de Referência (MM/AAAA)')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Adicional')),
                ('cliente_mensalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.clientemensalista', verbose_name='Cliente Mensalista')),
            ],
            options={
                'verbose_name': 'Cobrança de Mensalista',
                'verbose_name_plural': 'Cobranças de Mensalistas',
                'ordering': ['-mes_referencia', '-data_geracao'],
                'unique_together': {('cliente_mensalista', 'mes_referencia')},
            },
        ),
    ]
