# Generated by Django 4.2.23 on 2025-06-17 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CobrancaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10)),
                (
                    "nome_cliente",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pendente", "Pendente"), ("Pago", "Pago")],
                        default="Pendente",
                        max_length=10,
                    ),
                ),
                ("horario_entrada", models.DateTimeField()),
                ("horario_saida", models.DateTimeField()),
            ],
        ),
    ]
