# Generated by Django 4.2.23 on 2025-06-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cobrancadiaria",
            old_name="nome_cliente",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="cobrancadiaria",
            old_name="valor",
            new_name="valor_total",
        ),
    ]
