# Generated by Django 4.2.22 on 2025-06-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrancamensalista',
            name='cliente_mensalista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.mensalista', verbose_name='Cliente Mensalista'),
        ),
        migrations.DeleteModel(
            name='ClienteMensalista',
        ),
        migrations.DeleteModel(
            name='PlanoMensal',
        ),
    ]
