# Generated by Django 4.2.23 on 2025-06-13 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimento",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentos_registrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado Por",
            ),
        ),
        migrations.AddField(
            model_name="cobrancamensalista",
            name="cliente_mensalista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.clientemensalista",
                verbose_name="Cliente Mensalista",
            ),
        ),
        migrations.AddField(
            model_name="cobrancadiarista",
            name="movimento",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="pagamentos.movimento",
                verbose_name="Movimento de Estacionamento",
            ),
        ),
        migrations.AddField(
            model_name="clientemensalista",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pagamentos.planomensal",
                verbose_name="Plano Mensal",
            ),
        ),
        migrations.AddField(
            model_name="clientemensalista",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cobrancamensalista",
            unique_together={("cliente_mensalista", "mes_referencia")},
        ),
    ]
