# Generated by Django 4.2.22 on 2025-06-18 12:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_diarista_plano_alter_mensalista_plano'),
        ('pagamentos', '0002_rename_nome_cliente_cobrancadiaria_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaMensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('mes_referencia', models.CharField(help_text='Para cobranças mensais, ex: 05/2025', max_length=7, verbose_name='Mês de Referência (MM/AAAA)')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Adicional')),
                ('cliente_mensalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.mensalista', verbose_name='Cliente Mensalista')),
            ],
            options={
                'verbose_name': 'Cobrança de Mensalista',
                'verbose_name_plural': 'Cobranças de Mensalistas',
                'ordering': ['-mes_referencia', '-data_geracao'],
                'unique_together': {('cliente_mensalista', 'mes_referencia')},
            },
        ),
        migrations.CreateModel(
            name='cliente_mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('mes_referencia', models.CharField(help_text='Para cobranças mensais, ex: 05/2025', max_length=7, verbose_name='Mês de Referência (MM/AAAA)')),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Devido')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Adicional')),
                ('cliente_mensalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.mensalista', verbose_name='Cliente Mensalista')),
            ],
            options={
                'verbose_name': 'Cobrança de Mensalista',
                'verbose_name_plural': 'Cobranças de Mensalistas',
                'ordering': ['-mes_referencia', '-data_geracao'],
                'unique_together': {('cliente_mensalista', 'mes_referencia')},
            },
        ),
    ]
