# Generated by Django 5.1.6 on 2025-06-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_cobrancamensalista_cliente_mensalista_and_more'),
        ('pagamentos', '0002_initial'),
    ]

    operations = [
    ]
