# Generated by Django 4.2.21 on 2025-06-04 22:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntradaVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "placa",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                                "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                            )
                        ],
                    ),
                ),
                (
                    "horario_entrada",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaidaVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                                "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                            )
                        ],
                    ),
                ),
                ("tempo_permanencia", models.DurationField(blank=True, null=True)),
                (
                    "horario_saida",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saidas",
                        to="vagas.entradaveiculo",
                    ),
                ),
            ],
        ),
    ]
