# Generated by Django 4.2.23 on 2025-07-03 22:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entradaveiculo",
            name="tipo_veiculo",
        ),
        migrations.RemoveField(
            model_name="saidaveiculo",
            name="tipo_veiculo",
        ),
        migrations.AlterField(
            model_name="entradaveiculo",
            name="tipo_cliente",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="saidaveiculo",
            name="placa",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                        "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="saidaveiculo",
            name="tipo_cliente",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="solicitacaomanutencao",
            name="numero_vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vagas.vaga"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalVaga",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("numero", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Livre", "Livre"),
                            ("Manutenção", "Manutenção"),
                            ("Ocupada", "Ocupada"),
                        ],
                        default="Livre",
                        max_length=100,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vaga",
                "verbose_name_plural": "historical vagas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSolicitacaoManutencao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_solicitacao", models.DateTimeField(blank=True, editable=False)),
                ("resolvido", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "numero_vaga",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vagas.vaga",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical solicitacao manutencao",
                "verbose_name_plural": "historical solicitacao manutencaos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSaidaVeiculo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                                "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                            )
                        ],
                    ),
                ),
                ("tipo_cliente", models.CharField(max_length=12)),
                ("tempo_permanencia", models.DurationField(blank=True, null=True)),
                (
                    "horario_saida",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=8, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vagas.entradaveiculo",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical saida veiculo",
                "verbose_name_plural": "historical saida veiculos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEntradaVeiculo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo_cliente", models.CharField(max_length=12)),
                (
                    "placa",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                                "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                            )
                        ],
                    ),
                ),
                (
                    "horario_entrada",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical entrada veiculo",
                "verbose_name_plural": "historical entrada veiculos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
