# Generated by Django 4.2.23 on 2025-06-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradaveiculo",
            name="tipo_cliente",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="saidaveiculo",
            name="tipo_cliente",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="saidaveiculo",
            name="tipo_veiculo",
            field=models.CharField(max_length=10),
        ),
    ]
