# Generated by Django 4.2.22 on 2025-06-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Livre", "Livre"),
                            ("Manutenção", "Manutenção"),
                            ("Ocupada", "Ocupada"),
                        ],
                        default="Livre",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entradaveiculo",
            name="vaga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entradas",
                to="vagas.vaga",
            ),
        ),
    ]
