# Generated by Django 4.2.23 on 2025-06-16 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entradaveiculo",
            name="tipo_veiculo",
        ),
        migrations.RemoveField(
            model_name="saidaveiculo",
            name="tipo_veiculo",
        ),
        migrations.AlterField(
            model_name="entradaveiculo",
            name="tipo_cliente",
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name="saidaveiculo",
            name="placa",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                        "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="saidaveiculo",
            name="tipo_cliente",
            field=models.CharField(max_length=12),
        ),
    ]
