# Generated by Django 4.2.23 on 2025-06-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0002_alter_entradaveiculo_tipo_cliente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saidaveiculo",
            name="placa",
        ),
        migrations.RemoveField(
            model_name="saidaveiculo",
            name="tipo_cliente",
        ),
        migrations.RemoveField(
            model_name="saidaveiculo",
            name="tipo_veiculo",
        ),
    ]
