# Generated by Django 4.2.23 on 2025-06-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0002_remove_saidaveiculo_placa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacaomanutencao",
            name="numero_vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vagas.vaga"
            ),
        ),
    ]
