# Generated by Django 4.2.22 on 2025-06-05 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vagas", "0002_vaga_entradaveiculo_vaga"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_vaga", models.CharField(max_length=10)),
                ("descricao", models.TextField()),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("resolvido", models.BooleanField(default=False)),
                (
                    "solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
