# Generated by Django 5.0.4 on 2025-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('validade', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('tipo_plano', models.CharField(choices=[('Mensalista', 'Mensalista'), ('Diarista', 'Diarista')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, null=True)),
                ('valor_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_mensal', models.CharField(blank=True, choices=[('Mensal', 'Mensal'), ('Anual', 'Anual')], max_length=20, null=True)),
            ],
        ),
    ]
