# Generated by Django 4.2.21 on 2025-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planos",
            name="tipo_mensal",
            field=models.CharField(
                blank=True,
                choices=[("Mensal", "Mensal"), ("Anual", "Anual")],
                max_length=20,
                null=True,
            ),
        ),
    ]
