# Generated by Django 4.2.23 on 2025-07-03 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPlanos",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("validade", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("data_criacao", models.DateTimeField(blank=True, editable=False)),
                ("ultima_alteracao", models.DateTimeField(blank=True, editable=False)),
                (
                    "tipo_plano",
                    models.CharField(
                        choices=[
                            ("Mensalista", "Mensalista"),
                            ("Diarista", "Diarista"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                        default="Ativo",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "valor_diaria",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tipo_mensal",
                    models.CharField(
                        blank=True,
                        choices=[("Mensal", "Mensal"), ("Anual", "Anual")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical planos",
                "verbose_name_plural": "historical planoss",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
