# Generated by Django 5.0.4 on 2025-05-29 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diarista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(?\\d{2}\\)?[-.\\s]?\\d{4,5}[-.\\s]?\\d{4}$', 'Telefone no formato inválido (ex: (65) 99999-9999)')])),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}[0-9][A-Z][0-9]{2}$', 'Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)')])),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(?\\d{2}\\)?[-.\\s]?\\d{4,5}[-.\\s]?\\d{4}$', 'Telefone no formato inválido (ex: (65) 99999-9999)')])),
                ('email', models.EmailField(max_length=100)),
                ('plano', models.CharField(choices=[('Básico', 'Básico'), ('Integral', 'Integral'), ('Noturno', 'Noturno'), ('Empresarial', 'Empresarial')], max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}[0-9][A-Z][0-9]{2}$', 'Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)')])),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
