# Generated by Django 4.2.21 on 2025-05-25 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diarista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\(?\\d{2}\\)?\\s?\\d{4,5}\\-?\\d{4}$",
                                "Telefone inválido",
                            )
                        ],
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}-\\d{4}$",
                                "Placa no formato inválido (ex: ABC-1234)",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensalista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\(?\\d{2}\\)?\\s?\\d{4,5}\\-?\\d{4}$",
                                "Telefone inválido",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "plano",
                    models.CharField(
                        choices=[
                            ("Básico", "Básico"),
                            ("Integral", "Integral"),
                            ("Noturno", "Noturno"),
                            ("Empresarial", "Empresarial"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}-\\d{4}$",
                                "Placa no formato inválido (ex: ABC-1234)",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
