# Generated by Django 4.2.21 on 2025-05-26 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarista",
            name="placa",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}[0-9A-Z][0-9]{2}$",
                        "Placa no formato inválido (ex: ABC1D23 ou padrão Mercosul)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="diarista",
            name="telefone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\(?\\d{2}\\)?[-.\\s]?\\d{4,5}[-.\\s]?\\d{4}$",
                        "Telefone no formato inválido (ex: (65) 99999-9999)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mensalista",
            name="placa",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}[0-9A-Z][0-9]{2}$",
                        "Placa no formato inválido (ex: ABC1D23 ou padrão Mercosul)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mensalista",
            name="telefone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\(?\\d{2}\\)?[-.\\s]?\\d{4,5}[-.\\s]?\\d{4}$",
                        "Telefone no formato inválido (ex: (65) 99999-9999)",
                    )
                ],
            ),
        ),
    ]
