# Generated by Django 4.2.23 on 2025-06-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planos", "0001_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensalista",
            name="plano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mensalistas",
                to="planos.planos",
            ),
        ),
    ]
