# Generated by Django 4.2.23 on 2025-06-24 00:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("planos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0002_diarista_plano_alter_mensalista_plano"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMensalista",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\(?\\d{2}\\)?[-.\\s]?\\d{4,5}[-.\\s]?\\d{4}$",
                                "Telefone no formato inválido (ex: (65) 99999-9999)",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                (
                    "placa",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                                "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                            )
                        ],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo_plano": "Mensalista"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planos.planos",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mensalista",
                "verbose_name_plural": "historical mensalistas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDiarista",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\(?\\d{2}\\)?[-.\\s]?\\d{4,5}[-.\\s]?\\d{4}$",
                                "Telefone no formato inválido (ex: (65) 99999-9999)",
                            )
                        ],
                    ),
                ),
                (
                    "placa",
                    models.CharField(
                        db_index=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                                "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                            )
                        ],
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"tipo_plano": "Diarista"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="planos.planos",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical diarista",
                "verbose_name_plural": "historical diaristas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
