# Generated by Django 4.2.23 on 2025-06-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planos", "0001_initial"),
        ("clientes", "0002_alter_mensalista_plano"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarista",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo": "Diarista"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diaristas",
                to="planos.planos",
            ),
        ),
        migrations.AlterField(
            model_name="mensalista",
            name="plano",
            field=models.ForeignKey(
                limit_choices_to={"tipo": "Mensalista"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mensalistas",
                to="planos.planos",
            ),
        ),
    ]
