# Generated by Django 4.2.21 on 2025-05-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_alter_mensalista_placa"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensalista",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
