# Generated by Django 4.2.21 on 2025-05-29 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_mensalista_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diarista",
            name="placa",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{3}[0-9][A-Z][0-9]{2}$",
                        "Placa no formato inválido (ex: ABC1D23 - padrão Mercosul)",
                    )
                ],
            ),
        ),
    ]
