# Generated by Django 4.2.21 on 2025-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_alter_diarista_placa"),
    ]

    operations = [
        migrations.AddField(
            model_name="diarista",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
