# Generated by Django 4.2.23 on 2025-06-21 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatorioFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Relatório"),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Inicial")),
                ("data_fim", models.DateField(verbose_name="Data Final")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("editado_em", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Rascunho", "Rascunho"),
                            ("Finalizado", "Finalizado"),
                        ],
                        default="Rascunho",
                        max_length=10,
                    ),
                ),
                (
                    "total_emitido",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_pago",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_inadimplente",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="relatorios_pdfs/"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Financeiro",
                "verbose_name_plural": "Relatórios Financeiros",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
